# ==============================================
# КОНФИГУРАЦИОННЫЙ ФАЙЛ ДЛЯ TELEGRAM БОТА
# ==============================================

# Основные настройки бота
bot:
  token: "YOUR_TELEGRAM_BOT_TOKEN"  # Обязательно! Получить у @BotFather
  admin_ids: [123456789, 987654321]  # ID админов через запятую (узнать у @userinfobot)

# ==============================================
# КОМАНДЫ БОТА (отображаются в меню)
# ==============================================
commands:
  /start:
    text: |
      <b>Добро пожаловать!</b> 🚀
      
      Я многофункциональный бот с поддержкой:
      • Кнопок меню
      • Изображений
      • Рассылок
      • Задержек сообщений
      
      Выберите действие ниже 👇
    description: "Начать работу с ботом"
    reply_buttons:  # Кнопки под клавиатурой после команды /start
      - "Основное меню"
      - "Помощь"
      - "Контакты"
  
  /help:
    text: |
      <b>Список доступных команд:</b>
      
      /start - Начало работы
      /help - Эта справка
      /menu - Основное меню
      
      <i>Админ-команды:</i>
      /stats - Статистика
      /broadcast - Рассылка
    description: "Помощь по командам"
  
  /menu:
    text: "Выберите раздел:"
    inline_buttons:  # Встроенные кнопки в сообщении
      - text: "📊 Информация"
      - text: "🖼 Галерея"
      - text: "🔗 Ссылки"
      - text: "📅 Расписание"
    description: "Главное меню"
  
  /stats:
    description: "Статистика бота (админы)"
  
  /broadcast:
    description: "Массовая рассылка (админы)"

# ==============================================
# СООБЩЕНИЯ ДЛЯ НЕИЗВЕСТНЫХ КОМАНД
# ==============================================
unknown_message:
  text: "Извините, я не понимаю эту команду. Напишите /help для справки."
  backup_print: 1  # Задержка перед отправкой (имитация печати)

# ==============================================
# НАСТРОЙКИ КНОПОК (REPLY И INLINE)
# ==============================================
buttons:
  # REPLY-КНОПКИ (под клавиатурой)
  "Основное меню":
    text: "Вы вернулись в главное меню"
    reply_buttons:
      - "Информация"
      - "Галерея"
      - "Контакты"
  
  "Помощь":
    text: "Чем могу помочь?"
    backup: 0.5  # Задержка перед показом сообщения (секунды)
  
  # INLINE-КНОПКИ (в сообщении)
  "📊 Информация":
    text: "<b>Полезная информация:</b>\n\nЗдесь может быть ваш текст..."
    backup_print: 2  # Имитация печати (секунды)
  
  "🖼 Галерея":
    text: "Вот наши изображения:"
    image: "gallery.jpg"  # Путь к файлу изображения
    backup: 1  # Задержка перед отправкой
    inline_buttons:
      - text: "Фото 1"
        url: "https://example.com/photo1.jpg"  # Кнопка с внешней ссылкой
      - text: "Фото 2"
  
  "🔗 Ссылки":
    text: "Наши ресурсы:"
    inline_buttons:
      - text: "🌐 Сайт"
        url: "https://example.com"
      - text: "📱 Telegram"
        url: "https://t.me/channel"
      - text: "◀️ Назад"
  
  "📅 Расписание":
    text: "Наше расписание:"
    reply_buttons:
      - "Сегодня"
      - "Завтра"
      - "Неделя"
  
  # КОМБИНИРОВАННЫЙ ПРИМЕР С ЗАДЕРЖКАМИ
  "Специальное предложение":
    text: "Только сегодня! Скидка 20%"
    backup: 3  # Ждем 3 секунды перед отправкой
    image: "promo.jpg"
    backup_print: 2  # Имитируем печать 2 секунды
    inline_buttons:
      - text: "🔥 Получить скидку"
      - text: "❌ Закрыть"
