bot:
  token: "YOUR_TOKEN"
  parse_mode: "HTML"
  
# Настройки проверки подписки


commands:
  /start:
    text: |
      👋<b>Привет я бот сервера SpMine!</b>
    
      Чем я могу помочь?
    description: "Начать работу с ботом"
    image: "logo.jpg"  # Файл должен находиться в той же папке
    inline_buttons: ["Поддержка", "Нашел баг/дюп", "Увидел читера", "Набор в Модерацию", "Промокод", "Правила проекта", "Помощь по серверу", "Не могу зайти на сервер", "У меня украли аккаунт"]
  
  /support:
    text: |
      Написать в поддержку:
      @SpMineSupport
    description: "Обратится в поддержку"
    inline_buttons: 
      - text: "Написать в поддержку."
        url: "https://t.me/SpMineSupport?start=chat"
      - "Назад"
  
  

buttons:
  У меня украли аккаунт:
    text: |
      <b>Если украденный аккаунт был не привязан к боту тг, восстановить его не получится...</b>

      <blockquote>1. Проблема с доступом
      2. Никнейм
      3. Почту с которой приобретался донат
      4. Чеки переводов</blockquote>

      <i>Поддержка ответит настолько быстро насколько сможет!</i>
    inline_buttons:
      - text: "Написать в поддержку."
        url: "https://t.me/SpMineSupport?start=chat"
      - "Назад"
  
  Не могу зайти на сервер:
    text: |
      <b>Если у вас возникли проблемы со входом на наш сервер.</b>

      <blockquote>1. Включить/выключить впн и зайти еще раз
      2. Зайти на сервер используя айпи адрес: tg.SpMine.ru
      3. Проверить версию майнкрафта. Наш сервер доступен с версии 1.16.5 по версию 1.21.5</blockquote>
      
      <i>Если из списка ничего не помогло, обратитесьв поддержку.</i>
    image: "serv_logo.jpg"
    inline_buttons:
      - text: "Написать в поддержку."
        url: "https://t.me/SpMineSupport?start=chat"
      - "Назад"
  Главное меню:
    image: "logo.jpg"
    inline_buttons: ["Поддержка", "Нашел баг/дюп", "Увидел читера", "Набор в Модерацию", "Промокод", "Правила проекта", "Помощь по серверу", "Не могу зайти на сервер", "У меня украли аккаунт"]
    text: |
      👋<b>Привет я бот сервера SpMine!</b>
    
      Чем я могу помочь?
    image: "logo.jpg"
    inline_buttons: ["Поддержка", "Нашел баг/дюп", "Увидел читера", "Набор в Модерацию", "Промокод", "Правила проекта", "Помощь по серверу", "Не могу зайти на сервер", "У меня украли аккаунт"]
  
  Назад:
    image: "logo.jpg"
    inline_buttons: ["Поддержка", "Нашел баг/дюп", "Увидел читера", "Набор в Модерацию", "Промокод", "Правила проекта", "Помощь по серверу", "Не могу зайти на сервер", "У меня украли аккаунт"]
    text: |
      👋<b>Привет я бот сервера SpMine!</b>
    
      Чем я могу помочь?
    image: "logo.jpg"
    inline_buttons: ["Поддержка", "Нашел баг/дюп", "Увидел читера", "Набор в Модерацию", "Промокод", "Правила проекта", "Помощь по серверу", "Не могу зайти на сервер", "У меня украли аккаунт"]
  
  Поддержка:
    text: |
      Написать в поддержку:
      @SpMineSupport
    inline_buttons: 
      - text: "Написать в поддержку."
        url: "https://t.me/SpMineSupport?start=chat"
      - "Назад"
  
    
  "Нашел баг/дюп":
    text: |
      <b>Уважаемый игрок</b>

      Если вы нашли баг/дюп то напишите в поддержку @stprtgz

      <blockquote>1) Режим
      2) Суть бага/дюпа
      3) При каких обстоятельствах он проявляется    
      4) Свой никнейм на сервере</blockquote>
   

      <b>Мы устраним проблему в кратчайшие сроки.</b>

      <i>С уважением,</i> 
      <i>Администрация сервера</i>

    inline_buttons: 
      - text: "Написать в поддержку."
        url: "https://t.me/SpMineSupport?start=chat"
      - "Назад"
    
  "Увидел читера":
    text: |
      <b>Уважаемый игрок</b>
      
      Если вы увидели читера то пишите в Поддержку
      
    inline_buttons: 
      - text: "Написать в поддержку."
        url: "https://t.me/SpMineSupport?start=chat"
      - "Назад"
    
  "Набор в Модерацию":
    text: |
      <b>Уважаемый игрок</b>

      ✏️Мы хотели бы сообщить вам, что набор на должность стажера для нашего сервера будет открыт в момент открытия поста о наборе в наших сообществах. Мы рекомендуем вам следить за обновлениями и оповещениями в сообществах нашего сервера, чтобы быть в курсе открытия набора. 


      🔶Мы благодарим вас за ваш интерес в участии на нашем сервере и надеемся на ваше активное участие в будущих инициативах. Следите за обновлениями и ждите дополнительной информации о наборе на должность стажера. 


      <i>С уважением,</i>
      <i>Администрации сервера</i>
    inline_buttons: ["Назад"]
    
  Промокод: 
  - text: |
       <b>Вам подарок🎁</b>

       Введите код в игре:
       <code>/code discovery</code>
       
       <i>Промокод можно ввести всего 1 раз.</i>
    inline_buttons: ["Назад"]
  
  Зайти на сервер:
  - text: |
       <b>Хочешь зайти на наш сервер?</b>

       Вот его айпи:
       <code>mc.SpMine.ru</code>
       
       <i>Кликай по айпи чтобы скопировать его.</i>
    inline_buttons: ["Назад"]
 

unknown_message:
   text: "Такой команды я не знаю. Введи /start"
   inline_buttons: ["Главное меню"]
