bot:
  token: "7835895373:AAH5LoaK3MvNzWtIXUoNyzvN9mzki8wQ2fA"
  parse_mode: "HTML"
  
# Настройки проверки подписки


commands:
  /start:
    text: "❓Чем я могу помочь?"
    image: "logo.jpg"  # Файл должен находиться в той же папке
    inline_buttons: ["Поддержка", "Нашел баг/дюп", "Увидел читера", "Набор в Модерацию", "Промокод", "Правила проекта", "Помощь по серверу"]
  
  

buttons:
  Назад:
    backup_print: 1
    text: "❓Чем я могу помочь?"
    image: "logo.jpg"
    inline_buttons: ["Поддержка", "Нашел баг/дюп", "Увидел читера", "Набор в Модерацию", "Промокод", "Правила проекта", "Помощь по серверу"]
  Главное меню:
    backup_print: 1
    text: "❓Чем я могу помочь?"
    image: "logo.jpg"
    inline_buttons: ["Поддержка", "Нашел баг/дюп", "Увидел читера", "Набор в Модерацию", "Промокод", "Правила проекта", "Помощь по серверу"]
  
  Поддержка:
    text: |
      Написать в поддержку:
      @SpMineSupport
    inline_buttons: 
      - text: "Написать в поддержку."
        url: "https://t.me/SpMineSupport?start=chat"
      - "Назад"
  
    
  "Нашел баг/дюп":
    text: |
      <b>Уважаемый игрок</b>

      Если вы нашли баг/дюп то напишите в поддержку @stprtgz

      <blockquote>1) Режим
      2) Суть бага/дюпа
      3) При каких обстоятельствах он проявляется    
      4) Свой никнейм на сервере</blockquote>
   

      <b>Мы устраним проблему в кратчайшие сроки.</b>

      <i>С уважением,</i> 
      <i>Администрация сервера</i>

    inline_buttons: 
      - text: "Написать в поддержку."
        url: "https://t.me/SpMineSupport?start=chat"
      - "Назад"
    
  "Увидел читера":
    text: |
      <b>Уважаемый игрок</b>
      
      Если вы увидели читера то пишите в Поддержку
      
    inline_buttons: 
      - text: "Написать в поддержку."
        url: "https://t.me/SpMineSupport?start=chat"
      - "Назад"
    
  "Набор в Модерацию":
    text: |
      <b>Уважаемый игрок</b>

      ✏️Мы хотели бы сообщить вам, что набор на должность стажера для нашего сервера будет открыт в момент открытия поста о наборе в наших сообществах. Мы рекомендуем вам следить за обновлениями и оповещениями в сообществах нашего сервера, чтобы быть в курсе открытия набора. 


      🔶Мы благодарим вас за ваш интерес в участии на нашем сервере и надеемся на ваше активное участие в будущих инициативах. Следите за обновлениями и ждите дополнительной информации о наборе на должность стажера. 


      <i>С уважением,</i>
      <i>Администрации сервера</i>
    inline_buttons: ["Назад"]
    
  Промокод: 
  - text: |
       <b>Вам подарок🎁</b>

       Введите код в игре:
       <code>/code discovery</code>
       
       <i>Промокод можно ввести всего 1 раз.</i>
    inline_buttons: ["Назад"]
 

unknown_message:
   text: "Выберите вариант из меню или используйте /start"
   inline_buttons: ["Главное меню"]